---
  - name: Check if present
    stat:
      path: "{{ netdata_binary }}"
    register: netdata_present

  - debug: msg="netdata not installed"
    when: netdata_present.stat.exists == False

  - debug: msg="netdata installed"
    when: netdata_present.stat.exists == True

  - name: Install package dependencies
    apt:
      name: "{{ item }}"
    with_items: "{{ netdata_deps }}"
    when: netdata_present.stat.exists == False

  - name: Fetching netdata from git
    git:
      repo: https://github.com/firehol/netdata.git
      dest: "{{ netdata_install_dir }}"
      version: "{{ netdata_version }}"
      force: yes
    register: clone_or_pull

  - name: Build and install
    shell: "./netdata-installer.sh --install {{ netdata_install_dir }} --dont-wait"
    args:
      chdir: "{{ netdata_install_dir }}"
    when: clone_or_pull.changed == True
    notify: stop service

  - name: Creating config
    template:
     src: '{{item}}.j2'
     dest: '{{ netdata_install_dir }}/netdata/etc/netdata/{{item}}'
     force: yes
    with_items:
      - netdata.conf
      - stream.conf
    become: yes

  - meta: flush_handlers

  - name: Copy service file
    command: cp {{ netdata_install_dir }}/system/netdata.service /etc/systemd/system/netdata.service
#    when: clone_or_pull.changed == True and ansible_service_mgr == "systemd"
#    notify: start and enable

  - name: reloading systemd daemon
    systemd:
      daemon_reload: yes

  - name: start and enable
    systemd:
      name: netdata
      state: restarted
      enabled: yes

