---
  - name: Check if present
    stat:
      path: "{{ drn_binary }}"
    register: drn_present

  - debug: msg="netdata not installed"
    when: drn_present.stat.exists == False

  - debug: msg="netdata installed"
    when: drn_present.stat.exists == True

  - name: Install package dependencies
    apt:
      name: "{{ item }}"
    with_items: "{{ drn_deps }}"
    when: drn_present.stat.exists == False

  - name: Fetching netdata from git
    git:
      repo: https://github.com/firehol/netdata.git
      dest: "{{ drn_install_dir }}"
      version: "{{ drn_version }}"
      force: yes
    register: clone_or_pull

  - name: Build and install
    shell: "./netdata-installer.sh --install {{ drn_install_dir }} --dont-wait"
    args:
      chdir: "{{ drn_install_dir }}"
    when: clone_or_pull.changed == True
    notify: stop service

  - name: Creating config
    template:
     src: '{{item}}.j2'
     dest: '{{ drn_install_dir }}/netdata/etc/netdata/{{item}}'
     force: yes
    with_items:
      - netdata.conf
      - stream.conf
    become: yes

  - meta: flush_handlers

  - name: Copy service file
    command: cp {{ drn_install_dir }}/system/netdata.service /etc/systemd/system/netdata.service
    notify: start/restart netdata

  # - name: start and enable
  #   service:
  #     name: netdata
  #     state: restarted
  #     enabled: yes

