- name: stop service
  systemd:
    name: "{{drn_service}}"
    state: stopped
  when: drn_present.stat.exists == True

- name: start/restart netdata
  service:
    name: "{{drn_service}}"
    state: restarted
    enabled: yes
