- name: stop service
  systemd:
    name: netdata
    state: stopped
  when: drn_present.stat.exists == True

- name: start/restart netdata
  service:
    name: netdata
    state: restarted
    enabled: yes
