- name: stop service
  systemd:
    name: netdata
    state: stopped
  when: drn_present.stat.exists == True

- name: start/restart and enable
  systemd:
    name: netdata
    state: restarted
    enabled: yes
    daemon_reload: yes

